=== kiranTM36/web-XML/Lab 10/Application.xsd
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.inc.com"
    xmlns="http://www.inc.com"
    elementFormDefault="qualified"
>

    <xs:element name="Application">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="applicantID">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="APP-[0-9]{4}"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>

                <xs:element name="age">
                    <xs:simpleType>
                        <xs:restriction base="xs:integer">
                            <xs:minInclusive value="18"/>
                            <xs:maxInclusive value="60"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>

                <xs:element name="email">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value=".+@.+"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>

                <xs:element name="phoneNumber">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[0-9]{10}"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>

                <xs:element name="education">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="bachelorDegree"/>
                            <xs:enumeration value="masterDegree"/>
                            <xs:enumeration value="phd"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>

                <xs:element name="skills">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="skill"
                                type="xs:string"
                                minOccurs="1"
                                maxOccurs="5"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="experienceYears">
                    <xs:simpleType>
                        <xs:restriction base="xs:integer">
                            <xs:minInclusive value="0"/>
                            <xs:maxInclusive value="40"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>

                <xs:element name="portfolioURL" minOccurs="0">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="https?://.+"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== kiranTM36/web-XML/Lab 10/Application.xml
<Application
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://www.inc.com"
    xsi:schemaLocation="http://www.inc.com Application.xsd"
>

    <applicantID>APP-1234</applicantID>
    <age>20</age>
    <email>kiran@gmail.com</email>
    <phoneNumber>9827364010</phoneNumber>
    <education>phd</education>

    <skills>
        <skill>Writing</skill>
        <skill>Games</skill>
    </skills>

    <experienceYears>2</experienceYears>
    <portfolioURL>https://www.linkedin.com</portfolioURL>

</Application>
